import { Database } from 'bun:sqlite';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dbPath = process.env.DB_PATH || path.join(__dirname, 'data.sqlite');

export const db = new Database(dbPath);
db.exec('PRAGMA journal_mode = WAL;');
// WAL + synchronous NORMAL is the recommended pairing: without it Bun's
// SQLite stays at FULL and fsyncs the WAL on EVERY commit, which made a
// 200-record cmdlog batch cost 200 fsyncs. NORMAL only risks losing the
// last transactions on an OS crash, never corruption.
db.exec('PRAGMA synchronous = NORMAL;');

db.exec(`
  CREATE TABLE IF NOT EXISTS users (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    username    TEXT UNIQUE NOT NULL COLLATE NOCASE,
    salt        TEXT NOT NULL,
    hash        TEXT NOT NULL,
    iter        INTEGER NOT NULL,
    color       TEXT NOT NULL,
    avatar      TEXT,
    is_admin    INTEGER NOT NULL DEFAULT 0,
    created_at  INTEGER NOT NULL
  );

  CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS chat_sessions (
    id         TEXT PRIMARY KEY,
    user_id    INTEGER NOT NULL,
    title      TEXT NOT NULL,
    messages   TEXT NOT NULL,          -- JSON array of { role, content }
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_chat_user ON chat_sessions(user_id, updated_at DESC);

  -- Binary assets (Typst report screenshots + custom fonts). Only the
  -- metadata lives here; the bytes are files under ASSETS_DIR keyed by id.
  -- The workspace-facing record (display name, crop rect) is in the shared
  -- Yjs doc — this table is the server's own inventory of what it stores,
  -- so it can serve the right Content-Type and clean up orphaned files.
  CREATE TABLE IF NOT EXISTS assets (
    id          TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    kind        TEXT NOT NULL,          -- 'image' | 'font'
    filename    TEXT NOT NULL,          -- sanitized; also the Typst VFS name
    mime        TEXT NOT NULL,
    size        INTEGER NOT NULL,
    uploaded_by INTEGER,
    created_at  INTEGER NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_assets_ws ON assets(workspace_id, created_at DESC);

  -- Team command log. Each row is one whitelisted command captured by a
  -- btct-cmdlog agent on an operator's box and shipped here. This is the
  -- durable archive (unbounded); the shared Yjs doc holds only a bounded live
  -- window for the UI. The 'id' is generated by the agent (see cmdlog.mjs) so
  -- ingest is idempotent and the later exit/duration update finds its row.
  CREATE TABLE IF NOT EXISTS command_logs (
    id           TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    operator     TEXT NOT NULL,
    command      TEXT NOT NULL,          -- redacted unless the agent ran --no-redact
    tool         TEXT NOT NULL,          -- matched whitelist entry
    cwd          TEXT,
    host         TEXT,
    local_user   TEXT,
    shell_pid    INTEGER,
    started_at   INTEGER NOT NULL,       -- agent clock (epoch ms)
    received_at  INTEGER NOT NULL,       -- server clock — keeps skew debuggable
    exit_code    INTEGER,                -- NULL until the completion event lands
    duration_ms  INTEGER,
    redacted     INTEGER NOT NULL DEFAULT 1
  );
  CREATE INDEX IF NOT EXISTS idx_cmdlog_ws ON command_logs(workspace_id, started_at DESC);
  CREATE INDEX IF NOT EXISTS idx_cmdlog_op ON command_logs(workspace_id, operator, started_at DESC);
`);

// Best-effort migration for databases predating the is_admin column.
try {
  const cols = db.prepare(`PRAGMA table_info(users)`).all();
  if (!cols.some((c) => c.name === 'is_admin')) {
    db.exec(`ALTER TABLE users ADD COLUMN is_admin INTEGER NOT NULL DEFAULT 0`);
  }
  if (!cols.some((c) => c.name === 'avatar')) {
    db.exec(`ALTER TABLE users ADD COLUMN avatar TEXT`);
  }
  if (!cols.some((c) => c.name === 'prefs')) {
    db.exec(`ALTER TABLE users ADD COLUMN prefs TEXT`);
  }
} catch (err) {
  console.warn('[db] migration check failed:', err?.message || err);
}

const insertUser = db.prepare(
  `INSERT INTO users (username, salt, hash, iter, color, is_admin, created_at)
   VALUES ($username, $salt, $hash, $iter, $color, $is_admin, $created_at)`,
);
const findByUsername = db.prepare(
  `SELECT * FROM users WHERE username = ? COLLATE NOCASE`,
);
const findFullById = db.prepare(`SELECT * FROM users WHERE id = ?`);
const listAllUsers = db.prepare(
  `SELECT id, username, color, avatar, is_admin, created_at FROM users ORDER BY id ASC`,
);
const deleteUserById = db.prepare(`DELETE FROM users WHERE id = ?`);
const setAdminById = db.prepare(`UPDATE users SET is_admin = ? WHERE id = ?`);
const updatePasswordById = db.prepare(
  `UPDATE users SET salt = $salt, hash = $hash, iter = $iter WHERE id = $id`,
);
const setColorById = db.prepare(`UPDATE users SET color = ? WHERE id = ?`);
const setPrefsById = db.prepare(`UPDATE users SET prefs = ? WHERE id = ?`);
const countAdmins = db.prepare(
  `SELECT COUNT(*) AS n FROM users WHERE is_admin = 1`,
);

const PRESENCE_COLORS = [
  '#ef4444', '#f59e0b', '#10b981', '#3b82f6',
  '#8b5cf6', '#ec4899', '#14b8a6', '#f97316',
];

export function createUser({ username, salt, hash, iter, isAdmin = false }) {
  const color = PRESENCE_COLORS[Math.floor(Math.random() * PRESENCE_COLORS.length)];
  const info = insertUser.run({
    $username: username,
    $salt: salt,
    $hash: hash,
    $iter: iter,
    $color: color,
    $is_admin: isAdmin ? 1 : 0,
    $created_at: Date.now(),
  });
  return findFullById.get(Number(info.lastInsertRowid));
}

export function getUserByUsername(username) {
  return findByUsername.get(username) || null;
}

export function getUserById(id) {
  return findFullById.get(id) || null;
}

export function listUsers() {
  return listAllUsers.all().map((row) => ({
    id: row.id,
    username: row.username,
    color: row.color,
    isAdmin: !!row.is_admin,
    createdAt: row.created_at,
  }));
}

export function deleteUser(id) {
  deleteUserById.run(id);
}

export function setUserAdmin(id, isAdmin) {
  setAdminById.run(isAdmin ? 1 : 0, id);
}

export function updateUserPassword(id, { salt, hash, iter }) {
  updatePasswordById.run({ $id: id, $salt: salt, $hash: hash, $iter: iter });
}

export function updateUserColor(id, color) {
  setColorById.run(color, id);
}

// Per-account editor preferences (code-block accent color + custom keybinds),
// stored as a JSON blob. The shape is validated/normalized client-side and at
// the REST edge; here we just persist the serialized string.
export function updateUserPrefs(id, prefsJson) {
  setPrefsById.run(prefsJson, id);
}

export function adminCount() {
  return Number(countAdmins.get()?.n || 0);
}

// ── settings (key/value) ──
const getSettingStmt = db.prepare(`SELECT value FROM settings WHERE key = ?`);
const upsertSettingStmt = db.prepare(
  `INSERT INTO settings (key, value) VALUES ($key, $value)
   ON CONFLICT(key) DO UPDATE SET value = excluded.value`,
);

export function getSetting(key) {
  const row = getSettingStmt.get(key);
  return row ? row.value : null;
}

export function setSetting(key, value) {
  upsertSettingStmt.run({ $key: key, $value: value });
}

// ── Claude chat sessions (per-account, durable conversation history) ──
const listChatStmt = db.prepare(
  `SELECT id, title, created_at, updated_at FROM chat_sessions
   WHERE user_id = ? ORDER BY updated_at DESC`,
);
const getChatStmt = db.prepare(
  `SELECT id, title, messages, created_at, updated_at FROM chat_sessions
   WHERE id = ? AND user_id = ?`,
);
const upsertChatStmt = db.prepare(
  `INSERT INTO chat_sessions (id, user_id, title, messages, created_at, updated_at)
   VALUES ($id, $user_id, $title, $messages, $created_at, $updated_at)
   ON CONFLICT(id) DO UPDATE SET
     title = excluded.title,
     messages = excluded.messages,
     updated_at = excluded.updated_at
   WHERE chat_sessions.user_id = excluded.user_id`,
);
const deleteChatStmt = db.prepare(
  `DELETE FROM chat_sessions WHERE id = ? AND user_id = ?`,
);
// Keep only the newest N sessions per user.
const pruneChatStmt = db.prepare(
  `DELETE FROM chat_sessions WHERE user_id = ? AND id NOT IN (
     SELECT id FROM chat_sessions WHERE user_id = ? ORDER BY updated_at DESC LIMIT ?
   )`,
);
const CHAT_KEEP = 100;
const countChatStmt = db.prepare(
  `SELECT COUNT(*) AS n FROM chat_sessions WHERE user_id = ?`,
);

export function listChatSessions(userId) {
  return listChatStmt.all(userId).map((r) => ({
    id: r.id, title: r.title, createdAt: r.created_at, updatedAt: r.updated_at,
  }));
}

export function getChatSession(userId, id) {
  const r = getChatStmt.get(id, userId);
  if (!r) return null;
  let messages = [];
  try { const p = JSON.parse(r.messages); if (Array.isArray(p)) messages = p; } catch { /* corrupt → empty */ }
  return { id: r.id, title: r.title, messages, createdAt: r.created_at, updatedAt: r.updated_at };
}

export function saveChatSession(userId, { id, title, messages, createdAt, updatedAt }) {
  const now = Date.now();
  upsertChatStmt.run({
    $id: id,
    $user_id: userId,
    $title: String(title || 'New chat').slice(0, 200),
    $messages: JSON.stringify(messages ?? []),
    $created_at: Number(createdAt) || now,
    $updated_at: Number(updatedAt) || now,
  });
  // The prune subquery scans the user's sessions; only run it when the
  // cap is actually exceeded (the client saves after every assistant turn).
  if ((countChatStmt.get(userId)?.n ?? 0) > CHAT_KEEP) {
    pruneChatStmt.run(userId, userId, CHAT_KEEP);
  }
  return { id, title, createdAt: Number(createdAt) || now, updatedAt: Number(updatedAt) || now };
}

export function deleteChatSession(userId, id) {
  deleteChatStmt.run(id, userId);
}

// ── binary assets (Typst images + fonts) ──
const insertAssetStmt = db.prepare(
  `INSERT INTO assets (id, workspace_id, kind, filename, mime, size, uploaded_by, created_at)
   VALUES ($id, $workspace_id, $kind, $filename, $mime, $size, $uploaded_by, $created_at)`,
);
const getAssetStmt = db.prepare(`SELECT * FROM assets WHERE id = ?`);
const listAssetsStmt = db.prepare(
  `SELECT * FROM assets WHERE workspace_id = ? ORDER BY created_at DESC`,
);
const deleteAssetStmt = db.prepare(`DELETE FROM assets WHERE id = ?`);

function rowToAsset(r) {
  if (!r) return null;
  return {
    id: r.id,
    workspaceId: r.workspace_id,
    kind: r.kind,
    filename: r.filename,
    mime: r.mime,
    size: r.size,
    uploadedBy: r.uploaded_by,
    createdAt: r.created_at,
  };
}

export function createAsset({ id, workspaceId, kind, filename, mime, size, uploadedBy }) {
  insertAssetStmt.run({
    $id: id,
    $workspace_id: workspaceId,
    $kind: kind,
    $filename: filename,
    $mime: mime,
    $size: size,
    $uploaded_by: uploadedBy ?? null,
    $created_at: Date.now(),
  });
  return rowToAsset(getAssetStmt.get(id));
}

export function getAsset(id) {
  return rowToAsset(getAssetStmt.get(id));
}

export function listAssets(workspaceId) {
  return listAssetsStmt.all(workspaceId).map(rowToAsset);
}

export function deleteAssetRow(id) {
  deleteAssetStmt.run(id);
}

// ── command logs (team pentest command activity) ──
// Upsert keyed on the agent-generated id: the first write is the 'start' event
// (exit_code/duration_ms NULL); a later 'completion' event fills those in
// without touching the immutable command/metadata. A retried batch is a no-op.
const upsertCmdlogStmt = db.prepare(
  `INSERT INTO command_logs
     (id, workspace_id, operator, command, tool, cwd, host, local_user, shell_pid,
      started_at, received_at, exit_code, duration_ms, redacted)
   VALUES
     ($id, $workspace_id, $operator, $command, $tool, $cwd, $host, $local_user, $shell_pid,
      $started_at, $received_at, $exit_code, $duration_ms, $redacted)
   ON CONFLICT(id) DO UPDATE SET
     exit_code   = COALESCE(excluded.exit_code, command_logs.exit_code),
     duration_ms = COALESCE(excluded.duration_ms, command_logs.duration_ms)`,
);
const getCmdlogStmt = db.prepare(`SELECT * FROM command_logs WHERE id = ?`);
const clearCmdlogStmt = db.prepare(`DELETE FROM command_logs WHERE workspace_id = ?`);

function rowToCommandLog(r) {
  if (!r) return null;
  return {
    id: r.id,
    workspaceId: r.workspace_id,
    operator: r.operator,
    command: r.command,
    tool: r.tool,
    cwd: r.cwd,
    host: r.host,
    localUser: r.local_user,
    shellPid: r.shell_pid,
    startedAt: r.started_at,
    receivedAt: r.received_at,
    exitCode: r.exit_code,
    durationMs: r.duration_ms,
    redacted: !!r.redacted,
  };
}

// Upsert one command-log record and return the merged row. `receivedAt` is
// stamped by the caller (server clock).
export function upsertCommandLog(rec) {
  upsertCmdlogStmt.run({
    $id: rec.id,
    $workspace_id: rec.workspaceId,
    $operator: rec.operator,
    $command: rec.command,
    $tool: rec.tool,
    $cwd: rec.cwd ?? null,
    $host: rec.host ?? null,
    $local_user: rec.localUser ?? null,
    $shell_pid: rec.shellPid ?? null,
    $started_at: rec.startedAt,
    $received_at: rec.receivedAt,
    $exit_code: rec.exitCode ?? null,
    $duration_ms: rec.durationMs ?? null,
    $redacted: rec.redacted === false ? 0 : 1,
  });
  return rowToCommandLog(getCmdlogStmt.get(rec.id));
}

// Filtered read of the durable archive. `filters` fields are all optional;
// bind params are appended dynamically so unused filters cost nothing.
export function queryCommandLogs(filters = {}) {
  const clauses = ['workspace_id = ?'];
  const params = [filters.workspaceId];
  if (filters.operator) { clauses.push('operator = ?'); params.push(filters.operator); }
  if (filters.tool)     { clauses.push('tool = ?');     params.push(filters.tool); }
  if (filters.host)     { clauses.push('host = ?');     params.push(filters.host); }
  if (Number.isFinite(filters.from)) { clauses.push('started_at >= ?'); params.push(filters.from); }
  if (Number.isFinite(filters.to))   { clauses.push('started_at <= ?'); params.push(filters.to); }
  if (filters.q) { clauses.push('command LIKE ?'); params.push(`%${filters.q}%`); }
  if (filters.status === 'failed')  clauses.push('exit_code IS NOT NULL AND exit_code != 0');
  if (filters.status === 'success') clauses.push('exit_code = 0');
  if (filters.status === 'running') clauses.push('exit_code IS NULL');
  const limit = Math.min(Math.max(Number(filters.limit) || 1000, 1), 5000);
  const sql =
    `SELECT * FROM command_logs WHERE ${clauses.join(' AND ')} ORDER BY started_at DESC LIMIT ${limit}`;
  // db.query caches the compiled statement by SQL text (db.prepare compiles
  // a fresh one per call); the filter combinations are few, so every shape
  // ends up cached after first use.
  return db.query(sql).all(...params).map(rowToCommandLog);
}

/**
 * Upsert a whole ingest batch in ONE transaction: per-record implicit
 * transactions cost one WAL commit (and under synchronous=FULL, one fsync)
 * each, turning a 200-record agent batch into 200 disk syncs.
 */
export const upsertCommandLogBatch = db.transaction((records) =>
  records.map((r) => upsertCommandLog(r)));

export function clearCommandLogs(workspaceId) {
  clearCmdlogStmt.run(workspaceId);
}

export function publicUser(row) {
  if (!row) return null;
  return {
    id: row.id,
    username: row.username,
    color: row.color,
    isAdmin: !!row.is_admin,
    prefs: parsePrefs(row.prefs),
  };
}

// Defensive JSON parse for the stored prefs blob. Older rows (and rows that
// have never saved prefs) have NULL here; return an empty object so clients
// can merge their own defaults over it.
function parsePrefs(raw) {
  if (!raw) return {};
  try {
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
}
